# Generated by Django 4.0.6 on 2022-07-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Ficton', 'Ficton'), ('Non-Ficton', 'Non-Ficton'), ('History', 'History'), ('Geography', 'Geography'), ('Science', 'Science'), ('Horror', 'Horror'), ('Biographies', 'Biographies')], max_length=30)),
                ('synopsis', models.CharField(max_length=300)),
                ('isbn', models.CharField(max_length=12)),
                ('pages', models.IntegerField()),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Marathi', 'Marathi'), ('Gujarati', 'Gujarati'), ('Other', 'Other')], max_length=12)),
            ],
        ),
    ]
