# Generated by Django 4.0.6 on 2022-07-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_books_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Ficton', 'Non-Ficton'), ('History', 'History'), ('Geography', 'Geography'), ('Science', 'Science'), ('Horror', 'Horror'), ('Biographies', 'Biographies')], max_length=30),
        ),
    ]
